### ISSUE TITLE
Trailing whitespaces in markdown files cause commit failures

### ISSUE THREAD

**Issue by Haruhiist** [pdffiller/styleguide-hooks#30]
Commit fails if markdown files use trailing whitespaces instead of html <br> to force new line.
Instead of committing changes to a branch, git creates .tmp files in project directory and fails to commit. Can be due to outdated version of bash on all Mac OS X machines.

**Comment by MaxymVlasov** [comment]
Need rewrite to bash 3 compatible or to sh

**Comment by Haruhiist** [comment]
Not topical anymore.
